config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :attractions do 
    post '/rides', to: "rides#create"
  end

 "/attractions/:id/rides"

  root "home#index"

  get '/signin', to: "sessions#new"
  post '/signin', to: "sessions#create"
  delete '/signout', to: "sessions#destroy"

end

app/models/attraction.rb
class Attraction < ActiveRecord::Base
  # write associations here
  has_many :rides
  has_many :users, through: :rides
end

app/models/ride.rb
class Ride < ActiveRecord::Base
  # write associations here
  belongs_to :user
  belongs_to :attraction

  def take_ride
    message =  ["Sorry."]
    if user.tickets < attraction.tickets 
      message << "You do not have enough tickets the #{attraction.name}."
    end

    if user.height < attraction.min_height
      message << "You are not tall enough to ride the #{attraction.name}."
    end

    if message.length > 1
      message.join(" ")
    else
      take_the_ride 
    end


    # if self.user.tickets >= self.attraction.tickets && self.user.height >= self.attraction.min_height
    #   take_the_ride
    # elsif self.attraction.tickets >= self.user.tickets && you are tall enought
    #   "Sorry, you do not have enough tickets the #{attraction.name}."
    # elsif self.attraction.min_height >= self.user.height && you do have enought tickets
    #   "Sorry, you are not tall enough the #{attraction.name}."
    # eslif you are not tall enought && not enought tickets 
    # "Sorry, neighet "
    # end
  end

  def take_the_ride
    self.user.happiness += self.attraction.happiness_rating
    self.user.tickets -= self.attraction.tickets
    self.user.nausea += self.attraction.nausea_rating
    self.user.save
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # write associations here
  has_many :rides
  has_many :attractions, through: :rides

  def mood
    if self.happiness != nil && self.nausea != nil && self.happiness < self.nausea
      "sad"
    else
      "happy"
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/attractions_controller.rb
class AttractionsController < ApplicationController

  def index
    @attractions = Attraction.all
  end

  def show
    @attraction = Attraction.find_by(id: params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController

  def create
    @ride = Ride.create(attraction_id: params["attraction_id"], user_id: session[:user_id])
    @message = @ride.take_ride
    # binding.pry
    redirect_to @ride.user, notice: @message
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @users = User.all
  end

  def create
    # binding.pry
    @user = User.find_by(id: params["user"]["id"])
    if @user
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :new
    end
  end

  def destroy
    # binding.pry
    session[:user_id] = nil

    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    # binding.pry
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
      # redirect_to "/users/#{@user.id}"
      # redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    # binding.pry
    @user = User.find_by(id: params[:id])
    if flash[:notice] && flash[:notice].class != String
       flash.now[:notice] = "Thanks for riding the #{@user.rides.last.attraction.name}!"
    end
  end

  private 

    def user_params
      params.require(:user).permit(:name, :height, :happiness, :nausea, :tickets, :admin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/attractions/index.html.erb
<%@attractions.each do |attraction|%>
  <%=link_to "Go on #{attraction.name}", attraction_path(attraction)%>
  <%=attraction.min_height%>
  <%=attraction.happiness_rating%>
  <%=attraction.tickets%>
  <%=attraction.nausea_rating%>
<%end%>

app/views/attractions/show.html.erb
<%=@attraction.name%>
  <%=@attraction.min_height%>
  <%=@attraction.happiness_rating%>
  <%=@attraction.tickets%>
  <%=@attraction.nausea_rating%>

  <%=form_for([@attraction, Ride.new]) do |f|%>
    <%=f.submit "Go on this ride"%>
  <%end%>

app/views/home/index.html.erb
index.html.erb
You are on the home page!!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Amusement Park</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= analytics_init if Rails.env.production? %>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet"></link>
  </head>
  <body>
    <!--  navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        <a class="navbar-brand" href="<%= root_url %>"/>Home</a>
        <%=link_to "Sign up", new_user_path%>
        <%=link_to "Sign in", signin_path%>
        <%=link_to "Log Out", signout_path, method: :delete%>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
           <!--  nav here -->
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <!-- content -->
    <div class="container"  role="main">
      <%= yield %>
    </div>

  </body>
</html>

app/views/users/new.html.erb
<%=form_for @user do |f|%>
  <%=f.label :name%>
  <%=f.text_field :name%><br></br>

  <%=f.label :height%>
  <%=f.text_field :height%><br></br>

  <%=f.label :happiness%>
  <%=f.text_field :happiness%><br></br>

  <%=f.label :nausea%>
  <%=f.text_field :nausea%><br></br>

  <%=f.label :tickets%>
  <%=f.text_field :tickets%><br></br>

  <%=f.label :admin, "check this box if you are an owner"%>
  <%=f.check_box :admin%>
  <%=f.submit "Create User"%>
<%end%>

app/views/users/show.html.erb
Name: <%=@user.name%>
Height: <%=@user.height%>
Happiness: <%=@user.happiness%>
Nausea: <%=@user.nausea%>
Tickets: <%=@user.tickets%>
Mood: <%=@user.mood%>

<%if @user.admin%>
  ADMIN
  <%end%>

  <%=link_to "See attractions", attractions_path%>

  <%if flash[:notice]%>
  <%=flash[:notice]%>
  <%end%>